[package]
name = "resources"
version = "0.0.1"
authors = [ "guillem.cordoba@gmail.com" ]
edition = "2018"

[lib]
name = "resources"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde = "1"
derive_more = "0"

hdk3 = { path = "/home/guillem/projects/holochain/core/holochain/crates/hdk" }